# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine
GAMEPROJECTFILE =/home/michelle/documents/Unreal Projects/Pacman/Pacman.uproject

TARGETS = \
	Pacman-Linux-DebugGame  \
	Pacman-Linux-Shipping  \
	Pacman \
	PacmanEditor-Linux-DebugGame  \
	PacmanEditor-Linux-Shipping  \
	PacmanEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend PacmanEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug PacmanEditor-Linux-Debug


Pacman-Linux-DebugGame:
	 $(PROJECTBUILD) Pacman Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Pacman-Linux-Shipping:
	 $(PROJECTBUILD) Pacman Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Pacman:
	 $(PROJECTBUILD) Pacman Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

PacmanEditor-Linux-DebugGame:
	 $(PROJECTBUILD) PacmanEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

PacmanEditor-Linux-Shipping:
	 $(PROJECTBUILD) PacmanEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

PacmanEditor:
	 $(PROJECTBUILD) PacmanEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
